<section>    
    <article class="citation">
        <!-- boucle sur la citation -->
        <div>
            <?php foreach ($birthHeaders as $birthHeader) : ?>
            <p><?= $birthHeader['Content'] ?></p>
            <div class= "button">
                <form action ="index.php?controller=Admin\Manage&task=show&id=<?= $birthHeader['Id'] ?>"method="POST">
                    <input type="submit" value="modification">
                </form>
                <form action ="index.php?controller=Admin\Manage&task=delete&id=<?= $birthHeader['Id'] ?>" method="POST">
                    <input type="submit" value="suppression" onclick="return window.confirm(`Êtes vous sûr de vouloir supprimer cet article ?!`)">
                </form>
            </div>
            <?php endforeach ?>
        </div>
        <div>
            <img src="assets/images/Brigid's Grove.jpg" alt="Brigid's Grove">
        </div>
    <!-- boucle sur la citation -->
	</article>
</section>
<section>
    <article>
        <!-- boucle sur l'intro -->
        <?php foreach ($birthContents as $birthContent) : ?>
            <p><?= $birthContent['Content'] ?></p>
            <div class= "button">
                <form action ="index.php?controller=Admin\Manage&task=show&id=<?= $birthContent['Id'] ?>"method="POST">
                    <input type="submit" value="modification">
                </form>
                <form action ="index.php?controller=Admin\Manage&task=delete&id=<?= $birthContent['Id'] ?>" method="POST">
                    <input type="submit" value="suppression" onclick="return window.confirm(`Êtes vous sûr de vouloir supprimer cet article ?!`)">
                </form>
            </div>
        <?php endforeach ?>
        <!-- boucle sur l'intro -->
    </article>
</section>
<section>
    <article>
        <ul>
        <!-- boucle sur l'intro -->
        <?php foreach ($birthLists as $birthList) : ?>
            <li><?= $birthList['Content'] ?></li>
            <div class= "button">
                <form action ="index.php?controller=Admin\Manage&task=show&id=<?= $birthList['Id'] ?>"method="POST">
                    <input type="submit" value="modification">
                </form>
                <form action ="index.php?controller=Admin\Manage&task=delete&id=<?= $birthList['Id'] ?>" method="POST">
                    <input type="submit" value="suppression" onclick="return window.confirm(`Êtes vous sûr de vouloir supprimer cet article ?!`)">
                </form>
            </div>
        <?php endforeach ?>
        <!-- boucle sur l'intro -->
        </ul>
    </article>
</section>
<section>
    <article>
    <!-- boucle sur la conclusion -->
    <?php foreach ($birthFooters as $birthFooter) : ?>
        <p><?= $birthFooter['Content'] ?></p>
        <div class= "button">
            <form action ="index.php?controller=Admin\Manage&task=show&id=<?= $birthFooter['Id'] ?>"method="POST">
                <input type="submit" value="modification">
            </form>
            <form action ="index.php?controller=Admin\Manage&task=delete&id=<?= $birthFooter['Id'] ?>" method="POST">
                <input type="submit" value="suppression" onclick="return window.confirm(`Êtes vous sûr de vouloir supprimer cet article ?!`)">
            </form>
        </div>
    <?php endforeach ?>
    <!-- boucle sur la conclusion -->
	</article>
</section>
<section>    
    <article>
        <div>
        <!-- boucle sur la citation -->
        <?php foreach ($birthCitations as $birthCitation) : ?>
            <cite><?= $birthCitation['Content'] ?></cite>
            <div class= "button">
                <form action ="index.php?controller=Admin\Manage&task=show&id=<?= $birthCitation['Id'] ?>"method="POST">
                    <input type="submit" value="modification">
                </form>
                <form action ="index.php?controller=Admin\Manage&task=delete&id=<?= $birthCitation['Id'] ?>" method="POST">
                    <input type="submit" value="suppression" onclick="return window.confirm(`Êtes vous sûr de vouloir supprimer cet article ?!`)">
                </form>
            </div>
        </div>
    <?php endforeach ?>
    <!-- boucle sur la citation -->
	</article>
</section>