<section>
    <div>
        <img src="assets/images/Brigid's Grove.jpg" alt="Brigid's Grove">
    </div>
    <article class="citation">
        <!-- boucle sur la citation -->
        <div>
            <?php foreach ($perinatalHeaders as $perinatalHeader) : ?>
            <p><?= $perinatalHeader['Content'] ?></p>
            <div class= "button">
                <form action ="index.php?controller=Admin\Manage&task=show&id=<?= $perinatalHeader['Id'] ?>"method="POST">
                    <input type="submit" value="modification">
                </form>
                <form action ="index.php?controller=Admin\Manage&task=delete&id=<?= $perinatalHeader['Id'] ?>" method="POST">
                    <input type="submit" value="suppression" onclick="return window.confirm(`Êtes vous sûr de vouloir supprimer cet article ?!`)">
                </form>
            </div>
            <?php endforeach ?>
        </div>
    <!-- boucle sur la citation -->
	</article>
</section>
<section>
    <article>
        <!-- boucle sur l'intro -->
        <?php foreach ($perinatalContents as $perinatalContent) : ?>
            <p><?= $perinatalContent['Content'] ?></p>
            <div class= "button">
                <form action ="index.php?controller=Admin\Manage&task=show&id=<?= $perinatalContent['Id'] ?>"method="POST">
                    <input type="submit" value="modification">
                </form>
                <form action ="index.php?controller=Admin\Manage&task=delete&id=<?= $perinatalContent['Id'] ?>" method="POST">
                    <input type="submit" value="suppression" onclick="return window.confirm(`Êtes vous sûr de vouloir supprimer cet article ?!`)">
                </form>
            </div>
        <?php endforeach ?>
        <!-- boucle sur l'intro -->
    </article>
</section>
<section>
    <article>
        <ul>
        <!-- boucle sur l'intro -->
        <?php foreach ($perinatalLists as $perinatalList) : ?>
            <li><?= $perinatalList['Content'] ?></li>
            <div class= "button">
                <form action ="index.php?controller=Admin\Manage&task=show&id=<?= $perinatalList['Id'] ?>"method="POST">
                    <input type="submit" value="modification">
                </form>
                <form action ="index.php?controller=Admin\Manage&task=delete&id=<?= $perinatalList['Id'] ?>" method="POST">
                    <input type="submit" value="suppression" onclick="return window.confirm(`Êtes vous sûr de vouloir supprimer cet article ?!`)">
                </form>
            </div>
        <?php endforeach ?>
        <!-- boucle sur l'intro -->
        </ul>
    </article>
</section>
<section>
    <article>
    <!-- boucle sur la conclusion -->
    <?php foreach ($perinatalFooters as $perinatalFooter) : ?>
        <p><?= $perinatalFooter['Content'] ?></p>
        <div class= "button">
            <form action ="index.php?controller=Admin\Manage&task=show&id=<?= $perinatalFooter['Id'] ?>"method="POST">
                <input type="submit" value="modification">
            </form>
            <form action ="index.php?controller=Admin\Manage&task=delete&id=<?= $perinatalFooter['Id'] ?>" method="POST">
                <input type="submit" value="suppression" onclick="return window.confirm(`Êtes vous sûr de vouloir supprimer cet article ?!`)">
            </form>
        </div>
    <?php endforeach ?>
    <!-- boucle sur la conclusion -->
	</article>
</section>
<section>    
    <article>
        <div>
        <!-- boucle sur la citation -->
        <?php foreach ($perinatalCitations as $perinatalCitation) : ?>
            <cite><?= $perinatalCitation['Content'] ?></cite>
            <div class= "button">
                <form action ="index.php?controller=Admin\Manage&task=show&id=<?= $perinatalCitation['Id'] ?>"method="POST">
                    <input type="submit" value="modification">
                </form>
                <form action ="index.php?controller=Admin\Manage&task=delete&id=<?= $perinatalCitation['Id'] ?>" method="POST">
                    <input type="submit" value="suppression" onclick="return window.confirm(`Êtes vous sûr de vouloir supprimer cet article ?!`)">
                </form>
            </div>
        </div>
    <?php endforeach ?>
    <!-- boucle sur la citation -->
	</article>
</section>