<section>    
    <article class="citation">
        <!-- boucle sur la citation -->
        <div>
            <img src="assets/images/Brigid's Grove.jpg" alt="Brigid's Grove">
        </div>
        <div>
            <?php foreach ($postnatalHeaders as $postnatalHeader) : ?>
            <p><?= $postnatalHeader['Content'] ?></p>
            <div class= "button">
                <form action ="index.php?controller=Admin\Manage&task=show&id=<?= $postnatalHeader['Id'] ?>"method="POST">
                    <input type="submit" value="modification">
                </form>
                <form action ="index.php?controller=Admin\Manage&task=delete&id=<?= $postnatalHeader['Id'] ?>" method="POST">
                    <input type="submit" value="suppression" onclick="return window.confirm(`Êtes vous sûr de vouloir supprimer cet article ?!`)">
                </form>
            </div>
            <?php endforeach ?>
        </div>
    <!-- boucle sur la citation -->
	</article>
</section>
<section>
    <article>
        <!-- boucle sur l'intro -->
        <?php foreach ($postnatalContents as $postnatalContent) : ?>
            <p><?= $postnatalContent['Content'] ?></p>
            <div class= "button">
                <form action ="index.php?controller=Admin\Manage&task=show&id=<?= $postnatalContent['Id'] ?>"method="POST">
                    <input type="submit" value="modification">
                </form>
                <form action ="index.php?controller=Admin\Manage&task=delete&id=<?= $postnatalContent['Id'] ?>" method="POST">
                    <input type="submit" value="suppression" onclick="return window.confirm(`Êtes vous sûr de vouloir supprimer cet article ?!`)">
                </form>
            </div>
        <?php endforeach ?>
        <!-- boucle sur l'intro -->
    </article>
</section>
<section>
    <article>
        <ul>
        <!-- boucle sur l'intro -->
        <?php foreach ($postnatalLists as $postnatalList) : ?>
            <li><?= $postnatalList['Content'] ?></li>
            <div class= "button">
                <form action ="index.php?controller=Admin\Manage&task=show&id=<?= $postnatalList['Id'] ?>"method="POST">
                    <input type="submit" value="modification">
                </form>
                <form action ="index.php?controller=Admin\Manage&task=delete&id=<?= $postnatalList['Id'] ?>" method="POST">
                    <input type="submit" value="suppression" onclick="return window.confirm(`Êtes vous sûr de vouloir supprimer cet article ?!`)">
                </form>
            </div>
        <?php endforeach ?>
        <!-- boucle sur l'intro -->
        </ul>
    </article>
</section>
<section>
    <article>
    <!-- boucle sur la conclusion -->
    <?php foreach ($postnatalFooters as $postnatalFooter) : ?>
        <p><?= $postnatalFooter['Content'] ?></p>
        <div class= "button">
            <form action ="index.php?controller=Admin\Manage&task=show&id=<?= $postnatalFooter['Id'] ?>"method="POST">
                <input type="submit" value="modification">
            </form>
            <form action ="index.php?controller=Admin\Manage&task=delete&id=<?= $postnatalFooter['Id'] ?>" method="POST">
                <input type="submit" value="suppression" onclick="return window.confirm(`Êtes vous sûr de vouloir supprimer cet article ?!`)">
            </form>
        </div>
    <?php endforeach ?>
    <!-- boucle sur la conclusion -->
	</article>
</section>
<section>    
    <article>
        <div>
        <!-- boucle sur la citation -->
        <?php foreach ($postnatalCitations as $postnatalCitation) : ?>
            <cite><?= $postnatalCitation['Content'] ?></cite>
            <div class= "button">
                <form action ="index.php?controller=Admin\Manage&task=show&id=<?= $postnatalCitation['Id'] ?>"method="POST">
                    <input type="submit" value="modification">
                </form>
                <form action ="index.php?controller=Admin\Manage&task=delete&id=<?= $postnatalCitation['Id'] ?>" method="POST">
                    <input type="submit" value="suppression" onclick="return window.confirm(`Êtes vous sûr de vouloir supprimer cet article ?!`)">
                </form>
            </div>
        </div>
    <?php endforeach ?>
    <!-- boucle sur la citation -->
	</article>
</section>