<p>
    Je m'appelle Oriane, j'ai 28ans, je vis à Orléans.

Lors de la naissance de ma première fille,en 2013, je suis devenue maman; comme beaucoup, cela m'a transformée et a engendré une remise en question complète  ; je découvre le maternage, l'éducation bienveillante, la Communication Non Violente(une révolution dans mes relations!).
C'est pendant ma première grossesse que je découvre les doulas.

Pour la naissance de ma seconde fille, en 2015, j'ai souhaité un accouchement physiologique.
J'ai donc choisi une maternité réputée pour cela (Pithiviers), or j'ai accouchée sur la route, dans notre voiture, accompagnée de mon conjoint.
Malgré la peur que nous avons tous les deux ressenti, cette naissance nous a laissé un sentiment de grande puissance; puissance du corps, de l'amour, de la vie.

C'est ce sentiment que je souhaite transmettre aujourd'hui aux futurs parents !
</p>

<p>
    Si le féminisme a toujours été une norme dans ma vie, cela a pris une autre dimension après la naissance de ma deuxième fille.

J'ai cherché comment soutenir les femmes dans cette société où nous sommes sans cesse reléguées, objectifiées, comment les encourager à retrouver leur confiance, leur puissance et plus particulièrement autour de la maternité.

J'ai été bénévole au sein du Planning Familial, ce qui m'a permis de rencontrer des femmes engagées et inspirantes et ainsi de m'investir à leur côté au sein d'une association féministe locale .
</p>