<p>
    N'hésitez pas à me contacter, que vous soyez déjà parents ou que vous attendiez un enfant...
Mais aussi si vous avez envie de vous offrir (ou d'offrir) un moment de célébration autour de votre grossesse ou de partager un moment de sororité hors du temps.

Et parce que les doulas n'accompagnent pas que la joie, vous pouvez aussi me contacter si vous vous trouvez dans une période difficile, de deuil, de séparation, de doutes...

Je me rends disponible pour vous.

Vous pouvez me contacter via ce formulaire ou directement par mail ou par téléphone (WhatsApp et réseaux sociaux également).

Je me déplace à votre domicile dans le Loiret, si pour des raisons diverses et personnelles vous préférez que l'on se rencontre ailleurs c'est possible également !

J'ai hâte de vous rencontrer !
</p>