<!-- Login content -->
<section>
    <h2>Mon compte</h2>
    <form action="index.php?controller=user&task=login" method="POST">
        <fieldset>
            <legend>Se connecter</legend>
            <div class="field">
                <label>Mon adresse email</label>
                <div class="value"><input name="email" type="text"></div>
            </div>
            <div class="field">
                <label>Mon mot de passe</label>
                <div class="value"><input name="password" type="password"></div>
            </div>
            <br>
            <div class="field">
                <button class="button">Se connecter</button>
            </div>
        </fieldset>
    </form>
</section>

<!-- Login content -->