<!-- New user content -->
<section>
    <h2>Créer mon compte</h2>
    <form action="index.php?controller=user&task=create" method="POST">
        <fieldset>
            <div class="field">
                <label>Mon nom</label>
                <div class="value"><input name="lastname" type="text" required></div>
            </div>
            <div class="field">
                <label>Mon prénom</label>
                <div class="value"><input name="firstname" type="text" required></div>
            </div>
            <div class="field">
                <label>Mon adresse email</label>
                <div class="value"><input name="email" type="text" required></div>
            </div>
            <div class="field">
                <label>Mon mot de passe</label>
                <div class="value"><input name="password" type="password" required></div>
            </div>
            <div class="field">
                <label>Re-saisir à nouveau</label>
                <div class="value"><input name="password2" type="password" required></div>
            </div>
            <div class="field">
                <label>Mon adresse</label>
                <div class="value"><input name="address" type="text"></div>
            </div>
            <div class="field">
                <label>Ma ville</label>
                <div class="value"><input name="city" type="text"></div>
            </div>
            <div class="field">
                <label>Mon téléphone</label>
                <div class="value"><input name="phone" type="text"></div>
            </div>
            </br>
            <div class="field">
                <button class="button">Valider</button>
            </div>
        </fieldset>
    </form>
</section>
<!-- New user content -->
