<section>
    <h2>Ressources autour de la Périnatalité</h2>
    <div class="align">
        <?php foreach ($mediaLoirets as $mediaLoiret) : ?>
            <img src="<?=$mediaLoiret['FilesPath'].$mediaLoiret['Name'] ?>" alt="<?= $mediaLoiret['Content'] ?>">
        <?php endforeach ?>
    </div>
    <div class="perinatal">
        <article class="loiret">
            <div>
                <h3>Dans le Loiret</h3>
                <ul>
                <!-- boucle sur l'intro -->
                <?php foreach ($linksLoiret as $loiret) : ?>
                    <li><a href="<?= $loiret['Link'] ?>"><?= $loiret['Name'] ?></a></li>
                <?php endforeach ?>
                <!-- boucle sur l'intro -->
                </ul>
            </div>
            <div>
                <h3>Maternité du Loiret</h3>
                <ul>
                <!-- boucle sur l'intro -->
                <?php foreach ($linksMaternity as $maternity) : ?>
                    <li><a href="<?= $maternity['Link'] ?>"><?= $maternity['Name'] ?></a></li>
                <?php endforeach ?>
                <!-- boucle sur l'intro -->
                </ul>            
            </div>
            <div>
                <h3>Associations Loirétaines</h3>
                <ul>
                <!-- boucle sur l'intro -->
                <?php foreach ($linksAssociations as $associations) : ?>
                    <li><a href="<?= $associations['Link'] ?>"><?= $associations['Name'] ?></a></li>
                <?php endforeach ?>
                <!-- boucle sur l'intro -->
                </ul>            
            </div>
        </article>
        <article class="loiret">
            <h3>Autres</h3>
            <ul>
            <!-- boucle sur l'intro -->
            <?php foreach ($linksOther as $others) : ?>
                <li><a href="<?= $others['Link'] ?>"><?= $others['Name'] ?></a></li>
            <?php endforeach ?>
            <!-- boucle sur l'intro -->
            </ul>  
        </article>
    </div>
</section>
<section>
    <h2>Bibliothèque</h2>
    <div class="align">
    <?php foreach ($mediaLibraries as $mediaLibrarie) : ?>
        <img src="<?=$mediaLibrarie['FilesPath'].$mediaLibrarie['Name'] ?>" alt="<?= $mediaLibrarie['Content'] ?>">
    <?php endforeach ?>
    </div>
    <div class="align">
        <!-- boucle sur l'intro -->
        <?php foreach ($libraries as $librarie) : ?>
            <p><?= $librarie['Content'] ?></p>
        <?php endforeach ?>
        <!-- boucle sur l'intro -->
    </div>
    <div class="libraries">
        <article>
            <h3>Grossesse et Accouchement</h3>
            <ul>
            <!-- boucle sur l'intro -->
            <?php foreach ($pregnancys as $pregnancy) : ?>
                <li><?= $pregnancy['Content'] ?></li>
            <?php endforeach ?>
            <!-- boucle sur l'intro -->
            </ul>
        </article>
        <article>
            <h3>Post-Natal et Parentalité</h3>
            <ul>
            <!-- boucle sur l'intro -->
            <?php foreach ($postnatalLibraries as $postnatalLibrarie) : ?>
                <li><?= $postnatalLibrarie['Content'] ?></li>
            <?php endforeach ?>
            <!-- boucle sur l'intro -->
            </ul>
        </article>
        <article>
            <h3>Autour du féminin et du féminisme</h3>
            <ul>
            <!-- boucle sur l'intro -->
            <?php foreach ($feminisms as $feminism) : ?>
                <li><?= $feminism['Content'] ?></li>
            <?php endforeach ?>
            <!-- boucle sur l'intro -->
            </ul>
        </article>
        <article>
            <h3>Jeunesse</h3>
            <ul>
            <!-- boucle sur l'intro -->
            <?php foreach ($youths as $youth) : ?>
                <li><?= $youth['Content'] ?></li>
            <?php endforeach ?>
            <!-- boucle sur l'intro -->
            </ul>
        </article>
    </div>
</section>