<section>
    <div>
        <img src="assets/images/Brigid's Grove.jpg" alt="Brigid's Grove">
    </div>  
    <article class="citation">
        <div>
        <!-- boucle sur la citation -->
        <?php foreach ($perinatalHeaders as $perinatalHeader) : ?>
            <p><?= $perinatalHeader['Content'] ?></p>
        <?php endforeach ?>
        </div>
    <!-- boucle sur la citation -->
	</article>
</section>
<section>
    <article>
        <!-- boucle sur l'intro -->
        <?php foreach ($perinatalContents as $perinatalContent) : ?>
            <p><?= $perinatalContent['Content'] ?></p>
        <?php endforeach ?>
        <!-- boucle sur l'intro -->
    </article>
</section>
<section>
    <article>
        <ul>
        <!-- boucle sur l'intro -->
        <?php foreach ($perinatalLists as $perinatalList) : ?>
            <li><?= $perinatalList['Content'] ?></li>
        <?php endforeach ?>
        <!-- boucle sur l'intro -->
        </ul>
    </article>
</section>
<section>
    <article>
    <!-- boucle sur la conclusion -->
    <?php foreach ($perinatalFooters as $perinatalFooter) : ?>
        <p><?= $perinatalFooter['Content'] ?></p>
    <?php endforeach ?>
    <!-- boucle sur la conclusion -->
	</article>
</section>
<section>    
    <article>
        <div>
        <!-- boucle sur la citation -->
        <?php foreach ($perinatalCitations as $perinatalCitation) : ?>
            <cite><?= $perinatalCitation['Content'] ?></cite>
        </div>
    <?php endforeach ?>
    <!-- boucle sur la citation -->
	</article>
</section>