<section>
    <div>
        <img src="assets/images/Brigid's Grove.jpg" alt="Brigid's Grove">
    </div>  
    <article class="citation">
        <div>
        <!-- boucle sur la citation -->
        <?php foreach ($redTentHeaders as $redTentHeader) : ?>
            <p><?= $redTentHeader['Content'] ?></p>
        <?php endforeach ?>
        </div>
    <!-- boucle sur la citation -->
	</article>
</section>
<section>
    <article>
        <!-- boucle sur l'intro -->
        <?php foreach ($redTentContents as $redTentContent) : ?>
            <p><?= $redTentContent['Content'] ?></p>
        <?php endforeach ?>
        <!-- boucle sur l'intro -->
    </article>
</section>
<section>
    <article>
        <ul>
        <!-- boucle sur l'intro -->
        <?php foreach ($redTentDates as $redTentDate) : ?>
            <li><?= $redTentDate['Content'] ?></li>
        <?php endforeach ?>
        <!-- boucle sur l'intro -->
        </ul>
    </article>
</section>
<section>
    <article>
    <!-- boucle sur la conclusion -->
    <?php foreach ($redTentFooters as $redTentFooter) : ?>
        <p><?= $redTentFooter['Content'] ?></p>
    <?php endforeach ?>
    <!-- boucle sur la conclusion -->
	</article>
</section>
<section>    
    <article>
        <div>
        <!-- boucle sur la citation -->
        <?php foreach ($redTentCitations as $redTentCitation) : ?>
            <cite><?= $redTentCitation['Content'] ?></cite>
        </div>
    <?php endforeach ?>
    <!-- boucle sur la citation -->
	</article>
</section>