<h2>Tarifs et Modalités</h2>
<section>
    <article>
    <h3>Première rencontre</h3>
        <ul>
        <!-- boucle sur l'intro -->
        <?php foreach ($firstMeets as $firstMeet) : ?>
            <li><?= $firstMeet['Content'] ?></li>
            <div class= "button">
                <form action ="index.php?controller=Admin\Manage&task=show&id=<?= $firstMeet['Id'] ?>"method="POST">
                    <input type="submit" value="modification">
                </form>
                <!--<form action ="index.php?controller=Admin\Manage&task=delete&id=<?= $firstMeet['Id'] ?>" method="POST">-->
                    <input class="delete-btn" type="submit" value="suppression" data-id="<?= $firstMeet['Id'] ?>">
                </form>
            </div>
        <?php endforeach ?>
        <!-- boucle sur l'intro -->
        </ul>
    </article>
    <article>
    <h3>Séance individuelle, soutien périnatal</h3>
        <ul>
        <!-- boucle sur l'intro -->
        <?php foreach ($individualSessions as $individualSession) : ?>
            <li><?= $individualSession['Content'] ?></li>
            <div class= "button">
                <form action ="index.php?controller=Admin\Manage&task=show&id=<?= $individualSession['Id'] ?>"method="POST">
                    <input type="submit" value="modification">
                </form>
                <form action ="index.php?controller=Admin\Manage&task=delete&id=<?= $individualSession['Id'] ?>" method="POST">
                    <input type="submit" value="suppression" onclick="return validate()">
                </form>
            </div>
        <?php endforeach ?>
        <!-- boucle sur l'intro -->
        </ul>
    </article>
        <article>
    <h3>Séance inclue dans un forfait</h3>
        <ul>
        <!-- boucle sur l'intro -->
        <?php foreach ($packageSessions as $packageSession) : ?>
            <li><?= $packageSession['Content'] ?></li>
            <div class= "button">
                <form action ="index.php?controller=Admin\Manage&task=show&id=<?= $packageSession['Id'] ?>"method="POST">
                    <input type="submit" value="modification">
                </form>
                <form action ="index.php?controller=Admin\Manage&task=delete&id=<?= $packageSession['Id'] ?>" method="POST">
                    <input type="submit" value="suppression" onclick="return validate()">
                </form>
            </div>
        <?php endforeach ?>
        <!-- boucle sur l'intro -->
        </ul>
    </article>
        <article>
    <h3>Tente Rouge</h3>
        <ul>
        <!-- boucle sur l'intro -->
        <?php foreach ($redTentePrices as $redTentePrice) : ?>
            <li><?= $redTentePrice['Content'] ?></li>
            <div class= "button">
                <form action ="index.php?controller=Admin\Manage&task=show&id=<?= $redTentePrice['Id'] ?>"method="POST">
                    <input type="submit" value="modification">
                </form>
                <form action ="index.php?controller=Admin\Manage&task=delete&id=<?= $redTentePrice['Id'] ?>" method="POST">
                    <input type="submit" value="suppression" onclick="return validate()">
                </form>
            </div>
        <?php endforeach ?>
        <!-- boucle sur l'intro -->
        </ul>
    </article>
    <article>
    <h3>Blessing Way</h3>
        <ul>
        <!-- boucle sur l'intro -->
        <?php foreach ($blessingPrices as $blessingPrice) : ?>
            <li><?= $blessingPrice['Content'] ?></li>
            <div class= "button">
                <form action ="index.php?controller=Admin\Manage&task=show&id=<?= $blessingPrice['Id'] ?>"method="POST">
                    <input type="submit" value="modification">
                </form>
                <form action ="index.php?controller=Admin\Manage&task=delete&id=<?= $blessingPrice['Id'] ?>" method="POST">
                    <input type="submit" value="suppression" onclick="return validate()">
                </form>
            </div>
        <?php endforeach ?>
        <!-- boucle sur l'intro -->
        </ul>
    </article>
    <article>
    <h3>Soin Rituel Rebozo</h3>
        <ul>
        <!-- boucle sur l'intro -->
        <?php foreach ($rebozoRituals as $rebozoRitual) : ?>
            <li><?= $rebozoRitual['Content'] ?></li>
            <div class= "button">
                <form action ="index.php?controller=Admin\Manage&task=show&id=<?= $rebozoRitual['Id'] ?>"method="POST">
                    <input type="submit" value="modification">
                </form>
                <form action ="index.php?controller=Admin\Manage&task=delete&id=<?= $rebozoRitual['Id'] ?>" method="POST">
                    <input type="submit" value="suppression" onclick="return validate()">
                </form>
            </div>
        <?php endforeach ?>
        <!-- boucle sur l'intro -->
        </ul>
    </article>
</section>
<section>
    <h2>Forfaits</h2>
    <article>
    <h3>Un temps pour soi</h3>
        <ul>
        <!-- boucle sur l'intro -->
        <?php foreach ($timeYourselfs as $timeYourself) : ?>
            <li><?= $timeYourself['Content'] ?></li>
            <div class= "button">
                <form action ="index.php?controller=Admin\Manage&task=show&id=<?= $timeYourself['Id'] ?>"method="POST">
                    <input type="submit" value="modification">
                </form>
                <form action ="index.php?controller=Admin\Manage&task=delete&id=<?= $timeYourself['Id'] ?>" method="POST">
                    <input type="submit" value="suppression" onclick="return validate()">
                </form>
            </div>
        <?php endforeach ?>
        <!-- boucle sur l'intro -->
        </ul>
    </article>
    <article>
    <h3>Un accompagnement en continuité</h3>
        <ul>
        <!-- boucle sur l'intro -->
        <?php foreach ($continuousSupports as $continuousSupport) : ?>
            <li><?= $continuousSupport['Content'] ?></li>
            <div class= "button">
                <form action ="index.php?controller=Admin\Manage&task=show&id=<?= $continuousSupport['Id'] ?>"method="POST">
                    <input type="submit" value="modification">
                </form>
                <form action ="index.php?controller=Admin\Manage&task=delete&id=<?= $continuousSupport['Id'] ?>" method="POST">
                    <input type="submit" value="suppression" onclick="return validate()">
                </form>
            </div>
        <?php endforeach ?>
        <!-- boucle sur l'intro -->
        </ul>
    </article>
        <article>
    <h3>*Présence à l'accouchement</h3>
        <ul>
        <!-- boucle sur l'intro -->
        <?php foreach ($childbirths as $childbirth) : ?>
            <li><?= $childbirth['Content'] ?></li>
            <div class= "button">
                <form action ="index.php?controller=Admin\Manage&task=show&id=<?= $childbirth['Id'] ?>"method="POST">
                    <input type="submit" value="modification">
                </form>
                <form action ="index.php?controller=Admin\Manage&task=delete&id=<?= $childbirth['Id'] ?>" method="POST">
                    <input type="submit" value="suppression" onclick="return validate()">
                </form>
            </div>
        <?php endforeach ?>
        <!-- boucle sur l'intro -->
        </ul>
    </article>
</section>
<section>
    <article>
        <!-- boucle sur l'intro -->
        <?php foreach ($rules as $rule) : ?>
            <p><?= $rule['Content'] ?></p>
            <div class= "button">
                <form action ="index.php?controller=Admin\Manage&task=show&id=<?= $rule['Id'] ?>"method="POST">
                    <input type="submit" value="modification">
                </form>
                <form action ="index.php?controller=Admin\Manage&task=delete&id=<?= $rule['Id'] ?>" method="POST">
                    <input type="submit" value="suppression" onclick="return validate()">
                </form>
            </div>
        <?php endforeach ?>
        <!-- boucle sur l'intro -->
    </article>
</section>
<section>
    <article>
        <ul>
        <!-- boucle sur l'intro -->
        <?php foreach ($paiements as $paiement) : ?>
            <li><?= $paiement['Content'] ?></li>
            <div class= "button">
                <form action ="index.php?controller=Admin\Manage&task=show&id=<?= $paiement['Id'] ?>"method="POST">
                    <input type="submit" value="modification">
                </form>
                <form action ="index.php?controller=Admin\Manage&task=delete&id=<?= $paiement['Id'] ?>" method="POST">
                    <input type="submit" value="suppression" onclick="return validate()">
                </form>
            </div>
        <?php endforeach ?>
        <!-- boucle sur l'intro -->
        </ul>
    </article>
</section>
<section>
    <article>
        <!-- boucle sur l'intro -->
        <?php foreach ($arrangements as $arrangement) : ?>
            <p><?= $arrangement['Content'] ?></p>
            <div class= "button">
                <form action ="index.php?controller=Admin\Manage&task=show&id=<?= $arrangement['Id'] ?>"method="POST">
                    <input type="submit" value="modification">
                </form>
                <form action ="index.php?controller=Admin\Manage&task=delete&id=<?= $arrangement['Id'] ?>" method="POST">
                    <input type="submit" value="suppression" onclick="return validate()">
                </form>
            </div>
        <?php endforeach ?>
        <!-- boucle sur l'intro -->
    </article>
</section>