
<nav>
    <li><a>Accompagnement à la naissance</a></li>
    <li><a>Accompagnement post-natal</a></li>
    <li><a>Soutien périnatal</a></li>
    <li><a>Blessing way</a></li>
    <li><a>Tente rouge</a></li>
    <li><a>Tarifs & Modalités</a></li>
</nav>
<br>
<h2>Page des services</h2>
<button id="myModalBtn">Modifier</button>
<button>Supprimer</button>
<!-- The Modal -->
<div id="myModal" class="modal">
  <!-- Modal content -->
  <div class="modal-content">
    <span class="close">&times;</span>
        <form action="index.php?controller=&task=" method="POST" enctype="multipart/form-data">
        <fieldset>
			<textarea name="content" cols="30" rows="10" placeholder="Modifiez votre texte"></textarea>
            <input type="submit" value="Modifier">
        </fieldset>
    </form>
  </div>
</div>